version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      TRINITY_DATABASE_URL: postgres://postgres:iO6mhfDWsBV2EFOcPDsRCiBLi3fWxs8kHYkIpAbZPCPn6k4XCcBoXoh8yNtaU6cN@31.220.95.69:27543/postgres
      RAILS_MASTER_KEY: 10e856daa901523db5480e4487fe09b6
      JOB_CONCURRENCY: 2
    restart: always

  jobs:
    build:
      context: .
      dockerfile: Dockerfile
      target: jobs
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: 10e856daa901523db5480e4487fe09b6
      DATABASE_URL: postgres://postgres:SLkk2tcdgeFg15HXKqWU90ig6apVJHDkhDmAjb0oaHZTOtOjzHENNcYA5i2EWu1B@31.220.95.69:27542/postgres
      JOB_CONCURRENCY: 2
    restart: always
