version: "3.9"

services:
  web:
    build:
      context: ../../
      target: web
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    restart: always

  queue:
    build:
      context: ../../
      target: jobs
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - JOB_CONCURRENCY=2
    restart: always
    depends_on:
      - web
